[package]
name = "main"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
main = "53e83f34cc4b73bed84288213a4beca4262ad83cd5473c62bc0479e4db167a46"
launchpad_addr = "53e83f34cc4b73bed84288213a4beca4262ad83cd5473c62bc0479e4db167a46"
initial_creator_addr = "53e83f34cc4b73bed84288213a4beca4262ad83cd5473c62bc0479e4db167a46"
aptos_framework = "0x1"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-token-objects'

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"

